import logging
from datetime import datetime
from typing import Dict, Any

logger = logging.getLogger(__name__)

def generate_alert(source_agent: str, alert_type: str, severity: str, message: str) -> Dict[str, Any]:
    """
    Standardized alert generator.
    Ensures all modules produce alerts with the exact same schema.
    """
    alert = {
        # Simple ID generation for v1
        "alert_id": f"AL-{int(datetime.now().timestamp())}", 
        "source": source_agent,
        "type": alert_type,
        "severity": severity,
        "message": message,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "status": "Active"
    }
    
    logger.info(f"[{severity}] Alert generated by {source_agent}: {message}")
    
    # In future milestones, this service will also write the alert to the database
    return alert